### ISSUE TITLE
Problems installing on Ubuntu 14 - pyuv

### ISSUE THREAD

**Issue by phoebebright** [hitchtest/hitch#7]
Am trying to get hitch running with the example project and having a few issues:

Had this problem running hitch init in django-reminder example:

```
Building wheels for collected packages: pyuv
  Running setup.py bdist_wheel for pyuv
  Complete output from command /home/django/django-remindme/django-remindme-tests/.hitch/virtualenv/bin/python3 -c "import setuptools;__file__='/tmp/pip-build-tn3snbqg/pyuv/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpnfbxm6rcpip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-tn3snbqg/pyuv/setup.py", line 1
      ﻿# coding=utf-8
      ^
  SyntaxError: invalid character in identifier

  ----------------------------------------
  Failed building wheel for pyuv
```

Have managed to install it globally with help from SO but hitch is not recognising that.

**Comment by crdoconnor** [comment]
Verified. The problem seems to be fixed in the latest version of pyuv; my version was just lagging.

I've fixed by updating pyuv in hitchreqs: https://github.com/hitchtest/django-remindme-tests/commit/f570a4ccdf4db453830be0d20109db6a85b006aa#diff-6ab33e39420817ac3f6cbb7584878593L30

If you do a "git pull -u" and "git submodule update" in the django-remindme repo and try again, it shouldn't do this any more.

Thanks for reporting!
